version: '3.8'
services:
  frontend-login:
    build:
      context: ./frontend-login
      args:
        NEXT_PUBLIC_API_LOGIN: "http://localhost:8080"
        NEXT_PUBLIC_FRONT_INVENTARIO: "http://localhost:3001"
        NEXT_PUBLIC_FRONT_VENTAS: "http://localhost:3002"
        NEXT_PUBLIC_FRONT_FACTURACION: "http://localhost:3003"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_LOGIN=http://localhost:8080
      - NEXT_PUBLIC_FRONT_INVENTARIO=http://localhost:3001 
      - NEXT_PUBLIC_FRONT_VENTAS=http://localhost:3002
      - NEXT_PUBLIC_FRONT_FACTURACION=http://localhost:3003

  frontend-inventario:
    build: 
      context: ./frontend-inventario
      args:
        NEXT_PUBLIC_FRONT_LOGIN: "http://localhost:3000"
        NEXT_PUBLIC_API_INVENTARIO: "http://localhost:8081"
        NEXT_PUBLIC_API_VENTAS: "http://localhost:8082"
        NEXT_PUBLIC_API_FACTURACION: "http://localhost:8083"
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AIzaSyDNqVTuDN6yYgMkvpzB-zdp6rXDe8JjQtg"
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_FRONT_LOGIN=http://localhost:3000
      - NEXT_PUBLIC_API_INVENTARIO=http://localhost:8081
      - NEXT_PUBLIC_API_VENTAS=http://localhost:8082
      - NEXT_PUBLIC_API_FACTURACION=http://localhost:8083
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyDNqVTuDN6yYgMkvpzB-zdp6rXDe8JjQtg

  frontend-ventas:
    build: 
      context: ./frontend-ventas
      args:
        NEXT_PUBLIC_API_INVENTARIO: "http://localhost:8081"
        NEXT_PUBLIC_API_VENTAS: "http://localhost:8082"
        NEXT_PUBLIC_API_FACTURACION: "http://localhost:8083"
        NEXT_PUBLIC_FRONT_LOGIN: "http://localhost:3000"
        NEXT_PUBLIC_FRONT_FACTURACION: "http://localhost:3003"
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "AIzaSyDNqVTuDN6yYgMkvpzB-zdp6rXDe8JjQtg"
    ports:
      - "3002:3000"
    environment:
      - NEXT_PUBLIC_API_INVENTARIO=http://localhost:8081
      - NEXT_PUBLIC_API_VENTAS=http://localhost:8082
      - NEXT_PUBLIC_API_FACTURACION=http://localhost:8083
      - NEXT_PUBLIC_FRONT_LOGIN=http://localhost:3000
      - NEXT_PUBLIC_FRONT_FACTURACION=http://localhost:3003
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyDNqVTuDN6yYgMkvpzB-zdp6rXDe8JjQtg

  frontend-facturacion:
    build: 
      context: ./frontend-facturacion
      args:
        NEXT_PUBLIC_TOKEN_MERCADOPAGO: "TEST-4ae85150-41d0-48b6-aed4-d48ded2d0cbe"
        DEV_BACKEND_URL: "http://localhost:8083/"
        NEXT_PUBLIC_VENTAS_URL: "http://localhost:3002/"
    ports:
      - "3003:3000"
    environment:
      - NEXT_PUBLIC_TOKEN_MERCADOPAGO=TEST-4ae85150-41d0-48b6-aed4-d48ded2d0cbe
      - DEV_BACKEND_URL=http://localhost:8083/
      - NEXT_PUBLIC_VENTAS_URL=http://localhost:3002/

  backend-login:
    build: ./backend-login
    env_file:
      - ./backend-login/.env
    ports:
      - "8080:8080"

  backend-inventario:
    build: ./backend-inventario
    env_file:
      - ./backend-inventario/.env
    ports:
      - "8081:8080"

  backend-ventas:
    build: ./backend-ventas
    env_file:
      - ./backend-ventas/.env
    ports:
      - "8082:8080"

  backend-facturacion:
    build: ./backend-facturacion
    env_file:
      - ./backend-facturacion/.env
    ports:
      - "8083:8080"
