version: '3.8'
services:
  frontend-login:
    build:
      context: ./frontend-login
      args:
        NEXT_PUBLIC_API_LOGIN: ${NEXT_PUBLIC_API_LOGIN}
        NEXT_PUBLIC_FRONT_INVENTARIO: ${NEXT_PUBLIC_FRONT_INVENTARIO}
        NEXT_PUBLIC_FRONT_VENTAS: ${NEXT_PUBLIC_FRONT_VENTAS}
        NEXT_PUBLIC_FRONT_FACTURACION: ${NEXT_PUBLIC_FRONT_FACTURACION}
    ports:
      - "3000:3000"

  frontend-inventario:
    build: 
      context: ./frontend-inventario
      args:
        NEXT_PUBLIC_FRONT_LOGIN: ${NEXT_PUBLIC_FRONT_LOGIN}
        NEXT_PUBLIC_API_INVENTARIO: ${NEXT_PUBLIC_API_INVENTARIO}
        NEXT_PUBLIC_API_VENTAS: ${NEXT_PUBLIC_API_VENTAS}
        NEXT_PUBLIC_API_FACTURACION: ${NEXT_PUBLIC_API_FACTURACION}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    ports:
      - "3001:3000"

  frontend-ventas:
    build: 
      context: ./frontend-ventas
      args:
        NEXT_PUBLIC_API_INVENTARIO: ${NEXT_PUBLIC_API_INVENTARIO}
        NEXT_PUBLIC_API_VENTAS: ${NEXT_PUBLIC_API_VENTAS}
        NEXT_PUBLIC_API_FACTURACION: ${NEXT_PUBLIC_API_FACTURACION}
        NEXT_PUBLIC_FRONT_LOGIN: ${NEXT_PUBLIC_FRONT_LOGIN}
        NEXT_PUBLIC_FRONT_FACTURACION: ${NEXT_PUBLIC_FRONT_FACTURACION}
    ports:
      - "3002:3000"

  frontend-facturacion:
    build: 
      context: ./frontend-facturacion
      args:
        NEXT_PUBLIC_TOKEN_MERCADOPAGO: ${NEXT_PUBLIC_TOKEN_MERCADOPAGO}
        DEV_BACKEND_URLS: ${DEV_BACKEND_URLS}
    ports:
      - "3003:3000"

  backend-login:
    build: ./backend-login
    env_file:
      - ./backend-login/.env
    ports:
      - "8080:8080"

  backend-inventario:
    build: ./backend-inventario
    env_file:
      - ./backend-inventario/.env
    ports:
      - "8081:8080"

  backend-ventas:
    build: ./backend-ventas
    env_file:
      - ./backend-ventas/.env
    ports:
      - "8082:8080"

  backend-facturacion:
    build: ./backend-facturacion
    env_file:
      - ./backend-facturacion/.env
    ports:
      - "8083:8080"
